/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codeberry_datapath_windows_WindowsSystem */

#ifndef _Included_com_codeberry_datapath_windows_WindowsSystem
#define _Included_com_codeberry_datapath_windows_WindowsSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codeberry_datapath_windows_WindowsSystem
 * Method:    SHGetPathFromIDList
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_codeberry_datapath_windows_WindowsSystem_SHGetPathFromIDList
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
